version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: brownie
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: localhost
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: brownie

  frontend:
    build: ./frontend/brownieFront
    container_name: frontend_app
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  db_data:
